class CarsBrandsModels {
  static Map<String, List<String>> carsBrandsModels = {
    "Afa Romeo": [
      '156',
      '159',
      'Guilietta',
    ],
    "Audi": [
      'A1',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'A8',
      'E-Tron',
      'Other',
      'Q2',
      'Q3',
      'Q5',
      'Q7',
      'Q8',
      'RS3',
      'RS6',
      'S3',
      'S4',
      'S5',
      'S6',
      'S8',
    ],
    "BAIC": [
      'D20',
    ],
    "Bently": [
      'Bentayga',
      'Continental',
      'Continental GT',
      'Other',
    ],
    "BMW": [
      '1-Series',
      '2-Series',
      '3-Series',
      '4-Series',
      '5-Series',
      '6-Series',
      '7-Series',
      'IX',
      'M2',
      'M3',
      'M4',
      'M5',
      'M6',
      'Other',
      'X1',
      'X3',
      'X4',
      'X5',
      'X6',
      'XM',
      'Z4',
    ],
    "Buick": [
      'Regale',
    ],
    "BYD": [
      'F0',
      'F3r',
    ],
    "Cadillac": [
      'ATS',
      'BLS',
      'CTS',
      'DeVille',
      'Eldorado',
      'Escalade',
      'SRX',
    ],
    "Changan": [
      'CS',
      'Star',
    ],
    "Chery": [
      'E5',
      'Other',
    ],
    "Chevrolet": [
      'Aveo',
      'Blazer',
      'Camaro',
      'Captiva',
      'Cobalt',
      'Colorado',
      'Corvette',
      'Corvette Stingray',
      'Cruze',
      'Epica',
      'Equinox',
      'Menlo',
      'Monte Carlo',
      'Optra',
      'Silverado',
      'Sonic',
      'Spark',
      'Suburban',
      'Tahoe',
      'TrailBlazer',
      'Trax',
    ],
    "chrysler": [
      '300',
    ],
    "Citroen": [
      'Berlingo',
      'C3',
      'C4',
      'C5',
      'Other',
      'Xsara',
    ],
    "Dacia": [
      'Duster',
      'Lodgy',
      'Logan',
    ],
    "Daewoo": [
      'Racer',
    ],
    "Daihatsu": [
      'Kancil',
      'Sirion',
    ],
    "DFM": [
      'Other',
    ],
    "Dodge": [
      'Caravan',
      'Challenger',
      'Charger',
      'Dakota',
      'Daytona',
      'Durango',
      'Grand Caravan',
      'Other',
      'Ram',
    ],
    "Ferrari": [
      '458',
      'California',
      'F40',
    ],
    "Fiat": [
      '132',
      '500',
      '500L',
      'Abarth',
      'Bravo',
      'Doblo',
      'Other',
      'Punto',
    ],
    "Ford": [
      'Bronco',
      'Ecosport',
      'Escape',
      'Explorer',
      'F-Series',
      'Figo',
      'Focus',
      'Fusion',
      'Mustang',
      'Other',
      'Ranger',
      'Raptor',
      'Taurus',
    ],
    "GEELY": [
      'Emgrand',
      'LC Panda',
      'Other',
    ],
    "GMC": [
      'Acadia',
      'Canyon',
      'Denali',
      'Envoy',
      'Other',
      'Sierro',
      'Terrain',
      'Yukon',
    ],
    "Honda": [
      'Accord',
      'City',
      'Civic',
      'CR-V',
      'HR-V',
      'Odessey',
      'Other',
      'Pilot',
    ],
    "Hummer": [
      'H1',
      'H2',
      'H3',
      'Other',
    ],
    "Hyundai": [
      'Accent',
      'Creata-ix25',
      'Elantra',
      'Genesis',
      'Getz',
      'Grand i 10',
      'i10',
      'i20',
      'i30',
      'Ioniq',
      'Kona',
      'Santa Fe',
      'Solaris',
      'Sonata',
      'Tucson',
      'Veloster',
    ],
    "Infinity": [
      'EX',
      'FX',
      'G',
      'Q',
      'QX',
    ],
    "JAC": [
      'J4',
      'Other',
    ],
    "Jaguar": [
      'F-Pace',
      'F-Type',
      'S-Type',
      'X-Type',
      'XF',
      'XJ',
      'XK',
      'XK8',
      'Other',
    ],
    "Jeep": [
      'Cherokee',
      'Compass',
      'Gladiator',
      'Grand Cherokee',
      'Grand Cherokee Limiter',
      'Laredo',
      'Liberty',
      'Other',
      'Renegade',
      'Wrangler',
    ],
    "Kia": [
      'Cee\'d',
      'Cerato',
      'Forte',
      'Magentis',
      'Niro',
      'Optima',
      'Picanto',
      'Rio',
      'Rondo',
      'seltos',
      'Sorento',
      'Soul',
      'Sportage',
      'Other',
    ],
    "Lada": [
      'Kalina',
      'Niva',
      'Other',
    ],
    "Lamborghini": [
      'Gallardo',
      'Huracan',
      'Urus',
      'Other',
    ],
    "Land Rover": [
      'Defender',
      'Discover Sport',
      'LR2',
      'LR3',
      'LR4',
      'Other',
      'Rande Rover',
      'Rande Rover Evoque',
      'Rande Rover HSE',
      'Rande Rover HSE Sport',
      'Rande Rover Sport',
      'Rande Rover Super Charged',
      'Rande Rover Velar',
      'Rande Rover Vogue',
    ],
    "Lexus": [
      'GX',
      'IS',
      'LX',
      'NX',
      'RX',
      'SC',
    ],
    "Lincoln": [
      'Town Car',
    ],
    "Maserati": [
      'Ghibli',
      'GranCabrio',
      'GranTurismo',
      'Levante',
      'Quattroporte',
      'Other',
    ],
    "Mazda": [
      '2',
      '3',
      '323',
      '6',
      'CX-3',
      'CX-5',
      'CX-9',
      'Miata',
      'MPV',
      'Other',
    ],
    "Mercedes": [
      '200',
      '230',
      '230E',
      '240/260/280',
      '280C',
      '280S',
      '300/350/380',
      '300SEL',
      '400/420',
      '450 SL',
      '500/560',
      '500SEL',
      'A-Class',
      'AMG',
      'C-Class',
      'CL-CLass',
      'CLA',
      'CLK',
      'CLS',
      'E-Class',
      'G-Class',
      'GL-Class',
      'GLA',
      'GLC',
      'GLE',
      'GLK-Class',
      'GLS',
      'GT',
      'ML',
      'S-Class',
      'SL-Class',
      'SLC',
      'SLK',
      'V-Class',
      'Other',
    ],
    "Mini": [
      'Cabrio',
      'Cooper',
      'CooperS',
      'Countrymane',
      'Pacemam',
      'Other',
    ],
    "Mitsubishi": [
      'ASX',
      'Eclipse',
      'Evolution',
      'Lancer',
      'Mirage',
      'Montero',
      'Other',
      'Outlander',
      'Pajero',
      'Pajero Sport',
    ],
    "Nissan": [
      '350Z',
      'Altima',
      'Bluebird',
      'Frontire',
      'Juke',
      'Kickes',
      'Maxima',
      'Micra',
      'Murano',
      'Pathfinder',
      'Patrol',
      'Rogue',
      'Titan',
      'Versa',
      'X-trail',
      'Xterra',
      'Other',
    ],
    "Opel": [
      'Combo',
      'Corsa',
      'Insignia',
      'Kadett',
      'Other',
    ],
    "Peugeot": [
      '2008',
      '206',
      '301',
      '307',
      '308',
      '405',
      '406',
      '407',
      'Other',
    ],
    "Polestar": [
      '2',
      'Other',
    ],
    "Pontiac": [
      'Firebird',
      'Trans Am',
      'Other',
    ],
    "Porsche": [
      '911',
      '924',
      'Boxster',
      'Carrera 2',
      'Carrera GT',
      'Cayenne',
      'Cayenne S',
      'Carman',
      'Gts',
      'Macan',
      'Panamera',
      'Other',
    ],
    "Renault": [
      'Captur',
      'Clio',
      'Duster',
      'Kangoo',
      'Megan',
      'Sandero',
      'Scenic',
      'Talisman',
      'Twingo',
      'Twizy',
      'Zoe',
      'Other',
    ],
    "Roewe": [
      'Clever',
      'Other',
    ],
    "Rover": ['Other'],
    "Seat": [
      'Ibiza',
      'Leon',
      'Other',
    ],
    "Skoda": [
      'Fabia',
      'Superb',
      'Other',
    ],
    "Smart": [
      'ForFour',
      'ForTwo',
      'Other',
    ],
    "Ssang Yong": ['Other'],
    "Subaru": [
      'CrossTrek',
      'Forester',
      'Impreza',
      'Legacy',
      'Other',
      'WRX',
      'XV',
    ],
    "Suzuki": [
      'Baleno',
      'Celerio',
      'Ciaz',
      'Ertiga',
      'Grand Vitara',
      'Jimny',
      'Swift',
      'Other',
    ],
    "Tesla": [
      'Model 3',
      'Other',
    ],
    "Toyota": [
      '4Runner',
      'Avanza',
      'Camra',
      'Caserta',
      'Celica',
      'Corolla',
      'Corolla S',
      'Fortuner',
      'Prado',
      'RAV4',
      'Rush',
      'Sequoia',
      'Tundra',
      'Yaris',
      'Other',
    ],
    "Volkswagen": [
      'Beetle',
      'Caddy',
      'Caravelle',
      'Gol',
      'Golf-Serie',
      'Jetta',
      'Polo',
      'Passat',
      'Tiguan',
      'Touareg',
      'Other',
    ],
    "Volvo": [
      '740',
      'S60',
      'V40',
      'XC60',
      'XC90',
      'Other',
    ],
    "Ztye": [
      'Z-Series',
      'Other',
    ],
  };
  static List<String> bodyType = [
    '2 Door',
    '4 Door',
    'Coupe',
    'Light 4x4',
    'Sport',
    'SUV',
    'Sedan',
    'Saloon',
    'Other',
  ];
  static List<String> fuelType = [
    'Benzene',
    'Diesel',
    'Electric',
    'Hybrid Electric',
    'Other',
  ];
  static List<String> gearBox = [
    'Automatic',
    'Manual',
    'CVT',
    'Serni Auto',
    'Steptonic',
    'Tiptronic',
    'Other',
  ];
  static List<String> condition = [
    'Average',
    'Excellent',
    'Good',
    'New',
    'Poor',
  ];
  static List<String> years = [
    '1970',
    '1971',
    '1972',
    '1973',
    '1974',
    '1975',
    '1976',
    '1977',
    '1978',
    '1979',
    '1980',
    '1981',
    '1982',
    '1983',
    '1984',
    '1985',
    '1986',
    '1987',
    '1988',
    '1989',
    '1990',
    '1991',
    '1992',
    '1993',
    '1994',
    '1995',
    '1996',
    '1997',
    '1998',
    '1999',
    '2000',
    '2001',
    '2002',
    '2003',
    '2004',
    '2005',
    '2006',
    '2007',
    '2008',
    '2009',
    '2010',
    '2011',
    '2012',
    '2013',
    '2014',
    '2015',
    '2016',
    '2017',
    '2018',
    '2019',
    '2020',
    '2021',
    '2022',
    '2023',
    '2024'
  ];
  static List<String> cylinderSize = [
    'V10',
    'V12',
    'V8',
    'V6',
    'V4',
  ];
  static List<String> colors = [
    'Black',
    'Blue',
    'Bronze',
    'Brown',
    'Cream',
    'Gold',
    'Green',
    'Grey',
    'Maroon',
    'Not Specified',
    'Orange',
    'Pink',
    'Purple',
    'Red',
    'Silver',
    'Turquoise',
    'White',
    'Yellow',
    'Other',
  ];
}
